### ISSUE TITLE
Acceptance Tests for the Pin Management Menu

### ISSUE THREAD

**Issue by RichSchulz** [hpi-swa-teaching/SqueakMaps#19]

**Comment by RichSchulz** [comment]
setUp
	self wantsToTest: (SMAWindow new extent: 200@200; fullBounds; yourself).
	pinManagementButton := self subject findByLabel: 'manage pins and saved pins'.
	self savedPinsBefore: SMAWindow savedPins.
	SMAWindow savedPins: nil

tearDown
	SMAWindow savedPins: self savedPinsBefore.
	super tearDown

testDeleteAllPins
	| latLongMunich latLongBerlin |
	
	latLongMunich := 11.576124@48.137154.
	self subject placeCenteredPinAt: latLongMunich.
	latLongBerlin := 13.3888599@52.5170365.
	self subject placeCenteredPinAt: latLongBerlin.
	
	[pinManagementButton click] valueSupplyingAnswer: {'choose action to perform' . 'remove all pins'}.
	self assert: self subject tiledMapMorph pins isEmpty

testDeletePin
	| latLongMunich latLongBerlin berlinPins munichPins |
	
	latLongMunich := 11.576124@48.137154.
	self subject tiledMapMorph placePinAt: latLongMunich labeled: 'Munich'.
	latLongBerlin := 13.3888599@52.5170365.
	self subject tiledMapMorph placePinAt: latLongBerlin labeled: 'Berlin'.
	
	[pinManagementButton click] valueSupplyingAnswers: {{'choose action to perform' . 'remove a pin'} . {'choose a pin' . 'Berlin (13.3888599@52.5170365)'}}.
	berlinPins := self subject tiledMapMorph pins select: [:pin | pin latLong = latLongBerlin].
	munichPins :=  self subject tiledMapMorph pins select: [:pin | pin latLong = latLongMunich].
	self assert: berlinPins isEmpty.
	self assert: munichPins notEmpty

testDeleteSavedPin
	| latLongMunich latLongBerlin munichMarker berlinMarker berlinPins munichPins |
	
	latLongMunich := 11.576124@48.137154.
	latLongBerlin := 13.3888599@52.5170365.
	munichMarker := (MapLocationMarker new) label: 'München';
		latLong: latLongMunich.
	berlinMarker := (MapLocationMarker new) label: 'Berlin';
		latLong: latLongBerlin.	
	
	SMAWindow savedPins add: munichMarker; 
		add: berlinMarker.
	
	[pinManagementButton click] valueSupplyingAnswers: {{'choose action to perform' . 'delete a saved pin'} . {'choose a pin' . 'München (11.576124@48.137154)'}}.
	
	berlinPins := SMAWindow savedPins select: [:pin | pin latLong = latLongBerlin].
	munichPins :=  SMAWindow savedPins select: [:pin | pin latLong = latLongMunich].
	self assert: berlinPins notEmpty.
	self assert: munichPins isEmpty

testSaveAPin
	| latLongMunich |
	
	latLongMunich := 11.576124@48.137154.
	self subject tiledMapMorph placePinAt: latLongMunich labeled: 'München'.
	
	[pinManagementButton click] valueSupplyingAnswers: {{'choose action to perform' . 'save a pin'} . {'choose a pin' . 'München (11.576124@48.137154)'} . {'please set the name of the chosen pin' . 'save pin test'}}.
	self assert: ((SMAWindow savedPins collect: [:pin | pin label asString]) notEmpty).
	self assert: 1 equals: ((SMAWindow savedPins collect: [:pin | pin label asString]) indexOf: 'save pin test')

testShowASavedPin
	| latLongMunich munichMarker mapPins |
	
	latLongMunich := 11.576124@48.137154.
	munichMarker := (MapLocationMarker new) label: 'München';
		latLong: latLongMunich.
	
	SMAWindow savedPins add: munichMarker.
	
	[pinManagementButton click] valueSupplyingAnswers: {{'choose action to perform' . 'show a saved pin'} . {'choose a pin' . 'München (11.576124@48.137154)'}}.
	mapPins :=  self subject tiledMapMorph pins select: [:pin | pin latLong = latLongMunich].
	self assert: mapPins notEmpty.
	self assert: (MapTileLoader latLongToWorldPos: latLongMunich) equals: self subject tiledMapMorph center

**Comment by phoeinx** [comment]
Hi, danke für die coole Vorarbeit! 
Also die Tests schauen gut aus, nur laufen sie auf der CI nicht durch?
Für das "Ort durch Click Markieren" laufen die Tests ja durch, das habe ich mal akzeptiert.
Gibt es einen Test für "Pins als Liste anzeigen"?
