### ISSUE TITLE
Zoom view to match a given bounding box

### ISSUE THREAD

**Issue by richartkeil** [hpi-swa-teaching/SqueakMaps#23]
As a user I want the map to automatically zoom so that it matches a bounding box, so that I do not have to zoom out manually to see the places contained in the box.

Estimated Effort: 5

Actual: 6

**Comment by LeoKohlenberg** [comment]
Link Sammlung:

- https://nominatim.org/release-docs/develop/api/Output/#json

**Comment by LeoKohlenberg** [comment]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/82844368/167876653-c0529b65-62cb-4556-bcea-f72e2a8a173d.png">
????

**Comment by Durborough** [comment]
**Problem:**

- Das Zoom Level ist Device abhängig (sieht bei @TimRiedel anders aus als bei @Durborough ) --> Neues issue/neue User Story -> Verständnis von `computeTileMetrics`

**Comment by Durborough** [comment]
Die Funktionalität liegt nun in `locate: and:` an welche man zwei Query Strings übergeben kann. Die Funktion sucht zunächst mit der API die Location Daten, macht Pins draus, und berechnet aktuell mit einer Custom Bounding Box Berechnungsfunktion eine Boundingbox der zwei Punkte. Diese übergeben wir an `geocoder boundingBoxZoom:`, der uns ein dazu passendes Zoomlevel berechnet. Die custom Boundingboxberechnung ist demnächst unnötig, da die Routing API eine (bessere) Boundingbox der Route zurückgeben wird, die hier verwendet werden kann.
Wir berechnen den Mittelpunkt auf einer graden Linie in Weltkoordinaten zwischen den beiden Pins und nutzen ihn um die Karte darauf zu zentrieren.
Das Routenobjekt erhält die beiden Punkte. Hier kann später das Ergebnis der Routing API Abfrage eingefügt werden.
Die Pins werden abgespeichert.

**Known BUGS:**
- Zoomlevel ist Deviceabhängig (wahrscheinlich Bildschirmauflösung) -> Lösungsidee: Berechnung des Zoomlevels unter einbeziehung der Windowsize von unserer Karte
- Zoom nicht immer akkurat, sodass beide Pins im Bild angezeigt werden --> Mögliche Fehlerlocations: Custom Bounding Box Methode, komische Zoomlevelberechnung aus legacy Projekt, dass nur die Höhe der Boundingbox in Betracht zieht
- unsere `padding` Variable verändert nichts. Dies liegt vmtl. an oben genannten Deviceabhängigkeiten des Zoom Levels

**Infos:**
- Es wurde für die Boundingboxberechnung kein Refactoring des hässlichen Codes betrieben und auch keine Tests geschrieben, da in naher Zukunft die Boundingbox durch die API berechnet werden wird und die Methode dadurch redundant wird
