### ISSUE TITLE
Routing API Request and Format Parsing

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swa-teaching/SqueakMaps#25]
As a developer I want to be able to make a request to a routing API with given start and end location and parse the response into a format that can be used for displaying a route on the map later on.

Estimated effort: **8**
Acctual effort: **10**

**Comment by TimRiedel** [comment]
Temporary code that needs to be stored and needs to be implemented:
```
| apiKey latLongGriebnitzsee latLongHPI queryUrl json formatGriebnitzsee formatHPI features routeCoordinates window|

apiKey := '5b3ce3597851110001cf62480dc81045552b485d90dcd7291f831448'.
latLongGriebnitzsee := 13.117216@52.388978.
latLongHPI:= 13.128289@52.393838.


formatGriebnitzsee := latLongGriebnitzsee x asString, ',', latLongGriebnitzsee y asString. 
formatHPI := latLongHPI x asString, ',', latLongHPI y asString. 


queryUrl := ('https://api.openrouteservice.org/v2/directions/driving-car?api_key=', apiKey, '&start=', formatGriebnitzsee, '&end=', formatHPI) asUrl.

json := Json readFrom: queryUrl retrieveContents contentStream.
"(((json at: 'features') at: 'geometry') at: 'coordinates') do: [:coords |
	Transcript show: coords]."
features := json at: 'features'.
routeCoordinates := ((features at: 1) at: 'geometry') at: 'coordinates'.
routeCoordinates := routeCoordinates collect: [:coords | (coords at: 1) @ (coords at: 2)].


window := SMAWindow new.
window openInWorld.

window tiledMapMorph route points: routeCoordinates.
```

**Comment by TimRiedel** [comment]
Wir haben uns für die API OpenRouteService entschieden. Diese bietet zum einen einfache GET Requests für Start und Zielpunkt, bei denen man eine Bounding Box `bbox`, Richtungsanweisungen `steps`, Reisezeit `duration`, Distanz `distance` und die Geokoordinaten der Strecke `geometry, coordinates` erhält. Zudem kann man spezifizieren, ob man per Fahrrad, Auto, zu Fuß oder als Rollstuhlfahrer unterwegs sein will. Weiterhin bietet sie auch auch POST Requests für komplexere Anfragen (z.B. mehrere Wegpunkte) an.
Wir haben uns dazu entschieden, die Antworten im GeoJSON Format zu erwarten, da dies ein Standard für Geographische JSON Dateien zu sein scheint.

**Comment by JanniRoebbecke** [comment]
Additional Features:
- [x] Ungültige Eingaben abfangen (keine gültigen Koordinaten, kein valider API-Key, Punkte sind nicht erreichbar)
- [x] Routing service über die UI nutzbar machen. Wenn der Nutzer zwei Orte angegeben hat und auf "Go" klickt soll die Route zwischen den Orten erscheinen.
- [ ] Nutzer soll API-key eingaben können, die wir speichern und für die Abfragen benutzen. --> UserStory erstellt
- [ ] Wenn kein (valider) API-key angegeben ist oder der die tägliche möglichen Anfragen aufgebraucht sind, und der Nutzer ein Route abfragen will, soll er darüber informiert werden und die möglichekeit haben einen neuen API-key anzugeben. --> in obiger UserStory mitinbegriffen
- [ ] Auswahl des Verkehrsmittels ermöglichen --> UserStory erstellt

**Comment by TimRiedel** [comment]
So testet man den neuen Code:
```
| latLongStart latLongEnd ors route window apiKey|

latLongStart := 13.117216@52.388978.
latLongEnd := 361.128289@52.393838.
apiKey := '5b3ce3597851110001cf62480dc81045552b485d90dcd7291f831448'.

ors := SMAORSRoutingAPI new.
ors apiKey: apiKey.
route := ors getRouteFrom: latLongStart To: latLongEnd.

window := SMAWindow new.
window openInWorld.
window tiledMapMorph route: route.
```

**Comment by TimRiedel** [comment]
Die Benutzung der Routing API erfolgt so: Es müssen vorher die zwei Start- und Endkoordinaten berechnet werden. Anschließend setzt erstellt man ein neues `ORSRoutingAPI` Objekt und ruft `getRouteFrom: longLatStart To: longLatEnd.
` auf. Zurück bekommt man ein `Route` Objekt, dass die Waypoints in `points` speichert und zwei Geokoordinaten als Array in `boundingBox`.

Kann der API Service keine Route ermitteln, so wird ein Error geworfen, der die Message enthält, die die API uns gibt. Der Fehler muss bei der Benutzung abgefangen werden, sodass dann im UI ein Fenster für den Benutzer angezeigt wird.

Der API Key muss momentan noch manuell gesetzt werden, wir haben bereits eine User Story erstellt, damit der Benutzer den API Key genauso wie für Bing auch für ORS ändern kann.
```
apiKey := '5b3ce3597851110001cf62480dc81045552b485d90dcd7291f831448'.

orsAPI := SMAORSRoutingAPI new.
orsAPI apiKey: apiKey.
route := orsAPI getRouteFrom: latLongStart To: latLongEnd.
```

**Comment by Durborough** [comment]
Um den Spaß im System zu testen kann man diesen Methodenkörper in `locate: and:` einfügen:

`locate: aQueryString and: anotherQueryString

	| resultOne resultTwo firstPin secondPin routingAPI apiKey |

	resultOne := self geocoder locate: aQueryString.	
	resultTwo := self geocoder locate: anotherQueryString.	
	
	(resultOne isEmpty or: [resultTwo isEmpty]) ifTrue: [
		UIManager default inform: 'No results found.'.
		^ self].
	
	firstPin := resultOne first.
	secondPin := resultTwo first.
	self zoom: (self getZoomFrom: firstPin and: secondPin).
	self center: (self calculateMidPoint: (firstPin worldPos) and: (secondPin worldPos)).
	routingAPI := SMAORSRoutingAPI new.
	apiKey := '5b3ce3597851110001cf62480dc81045552b485d90dcd7291f831448'.

	routingAPI := SMAORSRoutingAPI new.
	routingAPI apiKey: apiKey.
	self route: (routingAPI getRouteFrom: (firstPin latLong)  To: (secondPin latLong)).
	"self route points: {firstPin latLong . secondPin latLong}."
	self pins: (Set newFrom: {firstPin . secondPin}).
	self layoutChanged.
	self changed`

**Comment by Durborough** [comment]
Mit Anpassung der `getBoundingBoxFrom: aJSON` Funktion in der Routing API
	getBoundingBoxFrom: aJSON
	| coordinates |
	
	coordinates := aJSON at: 'bbox'.
	^ { (coordinates second) . (coordinates fourth) . (coordinates first) . (coordinates third)}
	
kann man dann mit diesem Code
	
       locate: aQueryString and: anotherQueryString

	| resultOne resultTwo firstPin secondPin routingAPI apiKey zoom |

	resultOne := self geocoder locate: aQueryString.	
	resultTwo := self geocoder locate: anotherQueryString.	
	
	(resultOne isEmpty or: [resultTwo isEmpty]) ifTrue: [
		UIManager default inform: 'No results found.'.
		^ self].
	
	firstPin := resultOne first.
	secondPin := resultTwo first.
	
	self center: (self calculateMidPoint: (firstPin worldPos) and: (secondPin worldPos)).
	routingAPI := SMAORSRoutingAPI new.
	apiKey := '5b3ce3597851110001cf62480dc81045552b485d90dcd7291f831448'.

	routingAPI := SMAORSRoutingAPI new.
	routingAPI apiKey: apiKey.
	self route: (routingAPI getRouteFrom: (firstPin latLong)  To: (secondPin latLong)).
	
	zoom := self geocoder boundingBoxZoom: self route boundingBox.
	self zoom: (self tileSource clampZoom: zoom).
	self pins: (Set newFrom: {firstPin . secondPin}).
	self layoutChanged.
	self changed
	
	
Die tolle neue Funktionalität ausprobieren! Have Fun :)
