### ISSUE TITLE
Refactoring API System

### ISSUE THREAD

**Issue by JanniRoebbecke** [hpi-swa-teaching/SqueakMaps#34]
Hier wollten wir mögliche Refactorings des API-Systems aus dem Legacy Code sammenl und diskutieren

**Comment by JanniRoebbecke** [comment]
- [ ] (mögicherweise umbenenen) Die Testkategrorie APITests enthält tests der UI, zum auswählen der genutzten API. Man würde tests der API abfragen erwartetn.
- [ ] möglicherweise alle API-Klassen in die Kategorie SqueakMapsAPIs verschieben
- [ ] Ist es sinnvoll, dass der TiledMapMorph die routingAPI und die route speichert? Das macht das ganze System ziemlich unmodular.
- [ ] Im SMAWindow in der Methode `searchMultipleLocations` sollte nicht per default eine nicht konfigurierbare routing API gesetzt werden, sondern man sollte die vorher austauschen können, damit man bspw. in Tests den API Key setzen kann.
- [ ] Einige Tests stellen direkt Anfragen an APIs, z.B. `testMultipleLocationSearch`, 'testLocation...' wodurch der echte API Key in dem Test oder der Methode gespeichert werden muss. Das System muss so gestaltet werden, dass wir mittels eines Mock Objects die Anfragen stellen können, dann sind wir auch nicht vom Internet abhängig bei der Testausführung.

**Comment by TimRiedel** [comment]
Ich würde den Issue mal schließen, da die meisten TODOs schon von konkreteren Issues angesprochen werden.
