### ISSUE TITLE
Directions View

### ISSUE THREAD

**Issue by Glitterrosie** [hpi-swa-teaching/SqueakMaps#37]
As a user I want to have a directions view in the sidebar where I can input a start and destination    and see the drawn route on the map after pressing enter in order to plan a route.
**5**

**Comment by Glitterrosie** [comment]
Was uns eben beim Implementieren aufgefallen ist: das Window lässt sich beliebig skalieren. Das ist zwar eine schöne Funktion, wird aber problematisch, wenn wir eine Sidebar mit Submorphs haben. Diese könnten dann aus ihrem Frame rausfallen oder verschwinden. Das müssten wir uns aber nochmal anschauen, sobald die Sidebar fertig implementiert ist. Aber hier schonmal ein Lösungsvorschlag von uns: eine Minimum Size des Windows, sodass es beliebig groß werden kann, aber nicht beliebig klein.

**Comment by Durborough** [comment]
**Erkenntnisse so far:**
1. Wir können das mit der Sidebar umsetzen brauchen dafür aber eine klar definierte Schnittstelle. Diese müssten wir definieren. Siehe Punkt 2.
2. Durch die Sidebar als container für die Buttons kommt es zu einer zusätzlichen Indirektion beim Zugriff auf die Suchfunktion. Wir wären damit bei ca. 3 oder 4 Indirektionen zwischen Button Click und Suche mit API. Der Code wird super unverständlich und die Verbindung der Buttons mit der aktuell implementierten Funktionalität ist echt eklig.

Es wäre also smart da z.B. auf so ein "Model-View" Model umzusteigen, wie es aktuell nicht implementiert ist, aber viele anderen Anwendungen in Squeak das machen. Nur müssten wir uns dafür Gedanken machen, wie dieses aussehen sollte. Also was ist das Model? @richartkeil @LeoKohlenberg das betrifft auch euch bzw. insgesamt die Kommnikation zwischen Aussehen und Funktionalität. Zudem wäre es cool wenn man sich ein Smartes Widget System ausdenken würde, sodass nicht mehrfach Komponenten gebaut werden müssen. Ich glaube unsere bisherige Implementierung bietet dafür gute Ansätze.

Zudem könnten wir entscheiden, komplett auf reines Morphic umzusteigen und von den "Pluggable" Komponenten wegzukommen. Oder wollen wir das weiter mischen?

**tldr:**
Wie führen wir per Knopfdruck die Suchfunktion aus und wie bekommt die Suchfunktion die Input Daten? Durch die aktuelle Implementierung wird das eklig, also muss sich was ändern.

TODO: Model entscheiden

**Comment by Durborough** [comment]
**Known Bugs:**

- [ ] Suche starten mit Enter funktioniert nicht
- [ ] Spacing zwischen den einzelnen Komponenten nicht steuerbar
- [ ] rausfallen der morphs aus frame aufgrund nicht vorhandener minimal Size des Fensters

**Comment by richartkeil** [comment]
@LeoKohlenberg und ich haben gestern im Rahmen von #38 von Eurem Branch abgezweigt und darauf aufbauend eine Migration zum Toolbuilder-Approach durchgeführt. Dadurch müssen wir jetzt nicht mehr einzelne Morphs zusammenstecken und verwalten, sondern stecken im `SMAWindow` nur ein Bauplan in Form von "Specs" zusammen, welche der Toolbuilder dann später in konkrete Morphs gießt. Diesen Specs wird `SMAWindow` als Model übergeben, und sie können dann Methoden darauf aufrufen oder auf Änderungen reagieren.
Die tatsächlichen Morphs werden somit zu Observern vom Model. Dadurch entfallen die ganzen indirekten Zugriffe, da jeder Button, Input, usw. vom Toolbuilder eine Referenz zum Model erhält.

Dadurch kann jetzt auch dynamisch zur Laufzeit das Sidebar View getauscht werden, indem man im Model das `currentView` updated. Das Model speichert jetzt `searchInput`, `startSearchInput` und `destinationSearchInput`, welche immer die aktuellen Werte der entsprechenden Textfields enthalten. Der aktuelle Inhalt der Morph Inputs wird automatisch dorthin gespeichert. So kann die restliche Logik einfach auf diese Werte zugreifen, ohne von den Morphs wissen zu müssen.

Schaut gern mal in den Branch `feature/sidebar` — wenn von eurer Seite alles klar geht, könnten wir den dann in Euren Branch zurückmergen und diesen dann in `dev`.

**Comment by Glitterrosie** [comment]
Beim refactoring der Tests ist uns aufgefallen, dass in einigen Tests die Referenz auf das Model mit squeakMapsWindow benannt und manchmal mit model benannt wird. Das könnte man noch konsistenter gestalten!

**Comment by richartkeil** [comment]
Abgeschlossen in nochmal zusätzlich 2h. zu den 6h vorher also insgesamt 8h
