### ISSUE TITLE
Select Pin

### ISSUE THREAD

**Issue by richartkeil** [hpi-swa-teaching/SqueakMaps#39]
As a user I want to be able to only select one pin at a time by search or double click and see details of the pin in the left sidebar in order to take further actions.

**3**

**Comment by richartkeil** [comment]
Initial thoughts what is required:
- move GeoCoder to SMAWindow, so that the model talks to the API and provides the `locate:` and `locate:and:` functionality
- SMATiledMapMorph should only be responsible for displaying things (like a route line, or a list of provided pins)
- for that the SMATiledMapMorph keeps its pins list of SMAMapLocationMarkers
- but only the model has the ability to add or remove pins from this list
- the model stores a semantic (not visual) representation of the currently selected pin as SMAPin
- TileMapMorph should be able to notify SMAWindow about double clicks, so that the model can decide what to do with that (add it as waypoint to a route request, initiate a basic search, ...) → maybe store callback block?

→ the refactor of moving the geocoder to the model is necessary in order to get geocoded information for eg. display in the sidebar (or later route information in the sidebar)

**Comment by richartkeil** [comment]
Updates:
- `SMAMapLocationMarker` is now named `SMAGeocoderResult` to indicate that it represents a response including information like zoom
- `SMAWindow` stores a `selectedPin` of Type `SMAPin` → in the future all saved pins will be of this type
- this marker is updated through a search or when the user double clicks → in this case all _painted_ markers on the tiled map morph will be removed and a new _painted_ marker will be created at the position of the `selectedPin`

**Comment by Glitterrosie** [comment]
Tatsächliche Zeit:
Gemeinsam: 1h
Richard: 3h
Rosie: 3h

Gesamt: 7h
