### ISSUE TITLE
Pin Label Language

### ISSUE THREAD

**Issue by richartkeil** [hpi-swa-teaching/SqueakMaps#42]
As a user I want to be able to read the names of places/location markers, which don't use latin alphabet, as I am confused by Question marks as names (example: HPI as Search Input).

**3**

**Comment by TimRiedel** [comment]
Neuigkeiten aus 659cc27a0959cde9a638cc0fd4ef6c88e38da07f:
Im Nomatim Geocoder kann in der queryUrl der Paramter `accept-language=en-US` gesetzt werden, wodurch in der JSON Response keine "invaliden" (kyrillischen, chinesischen,...) Zeichen mehr enthalten sind. Diese konnte Squeak nicht anzeigen, da die Klasse `Json` diese nicht parsen konnte und somit schon im Json-Objekt nur Fragezeichen enthalten waren. Durch setzen der Sprache auf Englisch werden auch Orte wie Moskau korrekt angezeigt (Moscow).

**Comment by TimRiedel** [comment]
Es wurden die meisten Fragezeichen behoben, allerdings gibt die API z.B. wenn man `Charkiw` sucht auch noch kyrillische Buchstaben zurück, wo dann Fragezeichen angezeigt werden. Wir haben herausgefunden, dass die von Squeak verwendete default Font das nicht anzeigen kann. Genau gesagt kann keiner der vorinstallierten Fonts von Squeak kyrillische Buchstaben anzeigen. Es geht nur, wenn man sich selbst eine Font installiert, die dann aber lokal im Image gespeichert ist.
Wir werden uns nochmal im Slack erkundigen, ob man Fonts im Repo hinterlegen kann, sodass man diese dann automatisch auf die Label anwenden kann, ohne dass der User die vorher manuell installieren muss.

**Comment by TimRiedel** [comment]
Wir haben folgenden Aufruf in unserem Projekt:
`font := TexStyle defaultFont aCanvas drawString: aPin label at: labelPos font: font color: Color black.`
Dort möchten wir gerne die Font durch eine ersetzen, welche z.B. auch kyrillische Buchstaben anzeigt. Wir wollten das ganze gerne mit der Google Noto Sans Font probieren: https://fonts.google.com/noto/specimen/Noto+Sans.
Weil wir die Font gerne auch mit “shippen” wollen, haben wir den Inhalt der NotoSans-Regular.ttf in Form eines base64 encodeten Strings in einer Methode gespeichert, welche uns einen Stream zurückgibt, um die “simulierte Datei” einzulesen. Mit `TTFontReader readFrom: (SMAFonts notoSans)` erhalten wir dann auch erfolgreich eine `TTFontDescription`. Dann haben wir mit `TTCFont newTextStyleFromTT: (TTFontReader readFrom: (SMAFonts notoSans))` einen neuen TextStyle erzeugt und dann versucht in dem Aufruf oben die font durch `(TextStyle named: 'NotoSans') fontNamed: 'NotoSans'` zu ersetzen. Dann verändert sich auch die Schriftart, allerdings werden kyrillische Buchstaben immer noch nicht angezeigt und durch Fragezeichen dargestellt, obwohl wir verifiziert haben, dass die Font diese Zeichen zum Mindest im Browser abdeckt. Wir haben zum Testen auch mal die SegoeUI Font über den Importer installiert und wenn wir `(TextStyle named: 'SegoeUI') fontNamed: 'SegoeUI' ` als Font verwenden, werden die Buchstaben korrekt angezeigt. Jedoch passt die SegoeUI Font überhaupt nicht zu unserem Theme und ist auch nicht auf jedem Betriebssystem installiert.
Scheinbar machen wir noch irgendwas beim Import der Font falsch oder es ist wieder so ein Squeak internes Ding. Auf jeden Fall ist das jetzt der aktuelle Stand.
