### ISSUE TITLE
Allow to set ORS Key

### ISSUE THREAD

**Issue by richartkeil** [hpi-swa-teaching/SqueakMaps#44]
As a user I want to be able to add an API Key for OpenRouteServices in order to use different ORS accounts.

**2**

**Comment by JanniRoebbecke** [comment]
TODO:
- [x] löschen von Default Routenfindung mit Auto ("getRouteFrom: To:")
- [ ] zuvor gespeicherte API-keys werden zur zeit gelöscht, wenn der API-key gemanagen und dabei cancell aufgerufen wird.

**Comment by Durborough** [comment]
Auf dem Branch feature/routing-api-key kann man die aktuelle Version finden. Man kann unter dem Button "API Keys" die Option openrouteservice auswählen und in das auftauchende Fenster seinen API Key eingeben.
Ist dieser valide, funktioniert alles hervorragend.
Das Problem: Ist das API Key Feld leer oder enthält einen invaliden API Key, kann unser JSON Reader das Ergebnis nicht mehr lesen und wirft den Error (siehe Bild), obwohl von der API eine valide JSON mit einer Error Message drinne zurückgegeben wird.
Hat jemand eine Idee woran das liegen könnte und wie man das fixt @richartkeil @TimRiedel ? Denn aktuell können wir deshalb nicht überprüfen, ob ein API Key valide ist. 

![grafik](https://user-images.githubusercontent.com/76113613/172723773-e9286eeb-99c0-4720-9e24-d08e70836da1.png)

**Comment by TimRiedel** [comment]
Hey Ole, 
ich hab den Fehler auch mal debuggt und festgestellt, dass sich der Stream, von dem der Json Parser liest, unterscheidet, je nachdem ob ein Fehler auftritt oder nicht. Hier mal ein valides Ergebnis, dort steht nur die Json:

<img width="738" alt="valid API Key" src="https://user-images.githubusercontent.com/65392679/172786245-60c1fa11-a21f-4879-b383-27e471be3f0e.png">

Und hier ein invalides Ergebnis, dort stehen zusätzlich noch HTTP Informationen:

<img width="545" alt="invalid API Key" src="https://user-images.githubusercontent.com/65392679/172786440-45d9727c-8239-4dcd-b5ef-574d8073ff7a.png">

Ich vermute stark, dass der Fehler mit den zusätzlichen Informationen zusammenhängt. Ich hab auch mal invalide Routen getestet (z.B. Berlin Buenos Aires) und dort tritt der Fehler auch auf, weil im Gegensatz zu einer validen Route, zusätzliche Informationen in dem Stream stehen, die kein Json sind. 

Wenn wir nicht was übersehen, dann könnte das etwas komplizierter werden, da wir dann die API Anfragen anders stellen müssten, indem wir nicht direkt das Json lesen, sondern vorher noch die HTTP Informationen auswerten. Zudem müssten wir dann auch den JsonUrlReader anpassen, sodass wir in den Tests nicht nur die Json reingeben, sondern auch die ganzen Parameter mit dem Json als Stream. Momentan laufen z.B. die Tests für invalide Routen durch, weil wir nur das Json in den Tester stecken und das korrekt ausgelesen wird, aber in der Praxis schlagen invalide Routen wegen der zusätzlichen Parameter fehl (weil das dann ein Stream ist, der nicht nur das Json allein beinhaltet).

**Comment by TimRiedel** [comment]
Also das Problem liegt daran, dass die Klasse `HttpUrl` in einem Fehlerfall die ganzen HTTP Parameter vor dem content in die response packt, obwohl dort eigentlich nur der Json Code liegen sollte. Das simuliert wohl einen alten HTTP Socket, siehe hier:

<img width="893" alt="Bildschirmfoto 2022-06-09 um 10 34 23" src="https://user-images.githubusercontent.com/65392679/172803404-2477f8f5-6ebd-4b87-aab4-71d2834730a4.png">

**Comment by Durborough** [comment]
Lösungsideen:
1. Eigenen Reader schreiben der eine Klasse verwendet, die von `HttpUrl` erbt aber die Methode, die Fehlerhaft ist überschreibt. (Vmtl. die nachhaltigste Lösung, aberaufwendig)
2. Wir schreiben einen Wrapper, der die http Header Daten abschneidet. (Hacky aber weniger Aufwand)
3. Wir finden eine andere Methode, um die Anfragen an die API zu stellen.

**Comment by TimRiedel** [comment]
Ich debugge weiter und bin in regem Austausch mit Patrick im Slack: https://hpi-swa-teaching.slack.com/archives/C02GKUS21L4/p1654765128628019
Ich hoffe nicht, dass es nötig werden sollte einen eigenen Reader zu schreiben oder einen Wrapper zu bauen. Da muss es bereits irgendwas anderes in Squeak geben, schließlich sind wir ja nicht die ersten, die mal invalide Anfragen an eine API stellen und ein Json zurück bekommen wollen (hoffe ich zumindest :D)

**Comment by TimRiedel** [comment]
Neuigkeiten aus fc586c8d9686db344f12112555eb0a47b9a5513c:
Ich habe den HTTP Client zum `WebClient` geändert, sowohl in der Routing API als auch in den `locate` Methoden der Geocoder. Leider gibt die Routing API nicht immer konsistente Fehlermeldungen zurück, bspw. steht die Fehler Message bei invaliden Routen im Attribut `error -> message` während sie bei einem falschen API Key direkt im `error` Feld steht. Dafür habe ich eine neue Methode `handleErrorWith: aJsonObject` angelegt, die genau diese Fälle abtestet.
Die UI fängt die Fehlermeldungen jedoch noch nicht ab, daher tauchen die Fehler immer noch in dem Debugger Fenster auf.

Ich schlage vor im nächsten Sprint unbedingt mal die APIs zu refactorn, da die ganzen Tests für die anderen APIs ja direkt den Web Service anfragen und kein Mock Object nutzen. Um den Test `testMultipleSearchLocation` grün zu bekommen, musste ich den apiKey für die routingAPI direkt in der Methode `locate:and:by` auf dem `TiledMapMorhp` speichern, weil die routingAPI für den TiledMapMorph vom SMAWindow in jedem `searchMultipleLocations` neu gesetzt wird und somit überhaupt nicht modular ist.

@Durborough ihr könntet dann jetzt den Test einbauen, der den invaliden bzw. validen Api Key testet. Da wir es im nächsten Sprint eh mocken würden, könntet ihr auch gleich versuchen die Tests zu mocken, sofern das von der Architektur jetzt überhaupt geht.

**Comment by TimRiedel** [comment]
closed by PR #54
