### ISSUE TITLE
Invalid Numbers while searching some Routes

### ISSUE THREAD

**Issue by Glitterrosie** [hpi-swa-teaching/SqueakMaps#46]
Beim der Suche der Route von Berlin und Sydney taucht folgender Fehler auf:

![image](https://user-images.githubusercontent.com/64656859/171048286-c08f61b3-95e7-4f76-ac7d-dedb3d3346d8.png)

**Comment by richartkeil** [comment]
Gleiches bei der Suche nach `Shanghai` und `Alaska`.

Wir haben die entsprechenden Tests `testMultipleLocationSearchingBerlinSydney` und `testMultipleLocationSearchingShanghaiAlaska` erstmal deaktiviert. Wenn der Bug gefixt ist, sollten sie wieder angeschaltet werden.

**Comment by TimRiedel** [comment]
Der Fehler kommt von der API, denn die Route ist entweder zu lang oder das Ziel nicht erreichbar. Die Json wurde konnte Squeak aber nicht richtig auslesen, weil das mit dem verwendeten HTTP Client zusammen hängt. Ich habe das bereits gefixt, siehe auch folgender Issue: https://github.com/hpi-swa-teaching/SqueakMaps/issues/44

Stattdessen werfen wir jetzt eine eigene Fehlernachricht, die aber von der UI noch nicht abgefangen wird. Könnt ja nochmal auf dem "routing-api-key" verifizieren, ob es jetzt eine andere (korrekte) Fehlermeldung gibt (das wäre so gewollt) oder ob das Problem immer noch auftritt. Falls es korrekt ist, müssten halt noch die Tests angepasst werden, ich weiß nämlich jetzt nicht genau, was die an Rückgaben erwarten. Danach könnte der Issue auch geclosed werden.

**Comment by TimRiedel** [comment]
Hey @Glitterrosie @richartkeil, tritt der Fehler weiterhin noch auf oder kann der Issue zu?

**Comment by richartkeil** [comment]
Ah, jetzt kommt stattdessen folgender Fehler:
<img width="1042" alt="Screenshot 2022-06-30 at 14 14 54" src="https://user-images.githubusercontent.com/8680858/176674632-decdd718-9f0c-4609-a476-e49c995c46b0.png">

Idealerweise würden wir den wohl in einer Popup Nachricht dem Nutzer anzeigen, oder?

**Comment by TimRiedel** [comment]
Okay, das ist aber nicht schlimm, weil das Error Handling steht eh noch auf dem Plan, siehe #60. Ist nämlich ein Fehler, den wir werfen.
