### ISSUE TITLE
limit digits of displayed Route-Length

### ISSUE THREAD

**Issue by JanniRoebbecke** [hpi-swa-teaching/SqueakMaps#48]
As a user I wand the Number of Digits of the Route-Length, shown when searching a Route to be limited.

**1**

**Comment by JanniRoebbecke** [comment]
Sucht man die Route von Berlin nach Potsdam, wird die Länge der Route als Dezimalzahl mit vielen nicht nötwendigen Stellen, die die Routen-Dauer verdecken. angezeigt.
![grafik](https://user-images.githubusercontent.com/50395935/172712828-a6cc4588-20eb-47e8-bfc4-963ce2ad5589.png)

**Comment by richartkeil** [comment]
Actual Effort: 15min
