### ISSUE TITLE
Error when double-clicking on the ocean

### ISSUE THREAD

**Issue by Glitterrosie** [hpi-swa-teaching/SqueakMaps#50]
Beim Doppelklicken auf manche Orte, wie z.b. dem Meer kommt die untenstehende Fehlermeldung auf. Vermutung: wenn keine spezifische Ortsbezeichnung gefunden werden kann, wird ein Undefined Object indiziert.

**1**

![image](https://user-images.githubusercontent.com/64656859/173242220-c12fad04-2bb2-40aa-867f-c39e30887033.png)

**Comment by TimRiedel** [comment]
Das sollte nicht so schwer zu fixen sein, da einfach ein Json Objekt mit einem Error Field zurückgegeben wird und man dieses Feld abfangen kann. Man müsste sich nur überlegen was man in diesem Fall zurückgibt.

**Comment by TimRiedel** [comment]
Contained in #60
