### ISSUE TITLE
API Key Management

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swa-teaching/SqueakMaps#61]
As a developer I want to handle the API Keys in such a way, that I can use different modules of the system in other projects while keeping the architecture clean with few indirections.

**3**

**Comment by TimRiedel** [comment]
### API Keys
- [x] Sollten die API Keys wirklich auf dem `SMAWindow` gespeichert werden? Oder lieber auf Klassenseite der jeweiligen APIs? Insbesondere, wenn man beachtet, dass der `SearchManager` jetzt die APIs verwaltet und dies zu ziemlich langen Indirektionen führen kann, wenn man den API Key dann vom `SMAWindow` über den `SearchManager` auf der `RoutingAPI` setzt.
- [x] ~~Die `ORSRoutingAPI` speichert nach dem großen Refactor ihren API Key auf Klassenseite. Dieser refactor sollte wieder rückgängig gemacht werden, damit die RoutingAPI auch in anderen Projekten verwendet werden kann und nicht zu einer Art Singleton degeneriert.~~
- [x] Die SMAWindow Klasse speichert nun immer eine Instanz von allen APIs, beispielsweise um API-Keys zu verifizieren 

API-Key Management in die jeweiligen API Klassen verschieben da dies semantisch passender ist, die Modellierung an die Routing API angleicht, die große SMAWindow Klasse verschlankt und besser skaliert. Dies umfasst
- [x] API-Key werden auf Klassenseite der jeweiligen API gespeichert
- [x] API-Key checking in die APIs verschieben

**Comment by Glitterrosie** [comment]
Sicher @TimRiedel , dass der Key auf Instanzseite kommen soll? Dann müsste ich ja als Nutzer die Anwendung immer wieder neu einrichten (also den API Key neu eingeben), nachdem ich sie einmal geschlossen habe.

**Comment by TimRiedel** [comment]
Hey @Glitterrosie @JanniRoebbecke, könntet ihr vielleicht nochmal kurz ausführen, wie ihr zu der Entscheidung gekommen seid die API Keys jetzt doch auf der Klassenseite der APIs zu speichern? Ich sehe darin den Nachteil, dass nun keine zwei separaten Projekte existieren können, die beide das GeoService Package nutzen, weil in beiden der gleiche Key für die Routing API verwendet werden würde, wenn man ihn nur in einer Anwendung ändert. Gleiches gilt nach den Changes nun auch für das TiledMaps Package. Ihr schreibt zudem, dass ihr die anderen APIs an die RoutingAPI anpassen wolltet, wobei ja genau das refactoring in der RoutingAPI eigentlich rückgängig gemacht werden sollte, genau aus dem oben genannten Grund. 

Zudem habt ihr die Changes direkt auf dev gepusht, sodass wir kein Pull Request Review durchführen können. War wahrscheinlich nur ein Versehen, oder? Sollten noch Änderungen anstehen, könntet ihr dafür vielleicht noch einen eigenen Branch aufmachen?
