### ISSUE TITLE
Keyboard Input for Text Fields

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swa-teaching/SqueakMaps#67]
As a user I want to be able to search for a location or route when hitting Enter.

**2**

**Comment by richartkeil** [comment]
- wir haben die Tab-Funktionalität mal aus dem Issue entfernt, da das sehr kompliziert werden würde (wenn überhaupt möglich
- denn wir haben keine Referenzen auf Textfelder und können den Fokus nicht setzen
- da man sowieso nur in dem Feld schreiben kann, wo der Cursor grade drüber liegt, wäre die Frage was beim Tab drücken überhaupt genau passieren soll

**Comment by richartkeil** [comment]
Tatsächliche Zeit: 1.3h
