### ISSUE TITLE
Enforce Style Guide

### ISSUE THREAD

**Issue by richartkeil** [hpi-swa-teaching/SqueakMaps#73]
**3**

**Comment by Glitterrosie** [comment]
Ein paar Fragen, die sich gesammelt haben (schreibe ich auch alles ins Issue): 
1. Bei mir erschien schon vor dem Refactoren ein Error wenn ich auf Pins klicke
2. Nicht angefasst hab ich die mit den Implementors BCD, MK, cs, tonyg
