### ISSUE TITLE
Run Linter and cleanup code

### ISSUE THREAD

**Issue by richartkeil** [hpi-swa-teaching/SqueakMaps#74]
**3**

**Comment by richartkeil** [comment]
Gerade mal den kompletten Linter durchlaufen lassen:

<img width="732" alt="Screenshot 2022-07-19 at 09 21 02" src="https://user-images.githubusercontent.com/8680858/179690710-e2455da3-9c8c-4752-adfe-1bfcdbb0d420.png">
<img width="732" alt="Screenshot 2022-07-19 at 09 21 17" src="https://user-images.githubusercontent.com/8680858/179690764-b74cc712-20c5-409d-9fc5-f24388166020.png">
<img width="732" alt="Screenshot 2022-07-19 at 09 21 33" src="https://user-images.githubusercontent.com/8680858/179690813-b60ba2bb-a3ef-4450-a0c4-8ca3ee7728d9.png">
<img width="732" alt="Screenshot 2022-07-19 at 09 21 46" src="https://user-images.githubusercontent.com/8680858/179690862-8b484ba2-baf9-4f76-b3c4-e93e3a7daf19.png">
<img width="732" alt="Screenshot 2022-07-19 at 09 21 59" src="https://user-images.githubusercontent.com/8680858/179690905-e231d868-267c-4a07-95f6-84e0f4b705b1.png">
<img width="732" alt="Screenshot 2022-07-19 at 09 22 12" src="https://user-images.githubusercontent.com/8680858/179690949-8a09389e-c391-459a-a449-391010d9dc87.png">
<img width="732" alt="Screenshot 2022-07-19 at 09 22 27" src="https://user-images.githubusercontent.com/8680858/179690996-350e5f1e-6ac5-4833-a657-461da16929a2.png">

**Comment by Durborough** [comment]
**Methoden die weird sind, und noch verbessert werden müssen**

Im `SMAWindow`
- [x] `classVariableNames: 'SavedPins'` --> accessor klein schreiben, aber die klassenseitigen Variabeln groß schreiben, nochmal auf einheitlichkeit überprüfen
- [x] `searchDirections` und `searchLocation` haben leichte Code Dopplung und sind sehr lang besonders `searchDirections`
- [x]  `searchLocationFromCoordinates: aSMAGeoCoordinate` hier wird eine SMALocation zusammengebaut einfach so ohne Kommentar. Da sollte man nochmal drüber nachdenken.
- [x]  `apiKeyManagementOptions` und `apiSelcetionOptions `u.a. `ApiKey` vs `apiKey`, lange Methode, unübersichtlich, kapseln?
- [x] `handleError:`
- [x]  messagesWithoutSenders nochmal checken --> noch ein paar Sachen in den Building Methoden
- [x]  messages send but not implemented nochmal checken
- [ ]  handling of nil values nochmal checken
   - [ ] `calculateZoomForBoundingBox: aRectangle` --> Nil check. In Leos Version noch notwendig?
   - [ ] `selectedPin` --> nilCheck. Null Object möglich?
   - [ ] `self route` --> nilCheck. NullObject möglich?
- [x]  Refused Parent Bequest nochmal checken [Erklärung](https://refactoring.guru/smells/refused-bequest)
- [x]  inkonsequentes Naming pin oder marker z.B. in `selectedPin`, `buildPinSearchPanel`, etc.
- [x] hints of meta Programming nochmal checken --> `perform:` und `sendTo:` mag der nicht :/
- [x]  spelling Kategorie nochmal checken
- [x] in den build Methoden gibt es ein Frame der ein wenig anders parametirisiert immer wieder benutzt werden könnte... ist aber schon ein Konstruktor... soll man den jetzt nochmal extra kapseln?
- [x] Builder auslagern?
- [x] Klassen Kommentare `SMAMapConfigurator` und `SMASearchManager` fehlen

**Comment by Durborough** [comment]
Weirde Methoden, die wir uns nochmal angucken sollte:

Im `SMAWindow`:
- `apiKeyManagementOptions`
- `searchDirections`
- `searchLocation` und `searchLocationFromCoordinates: aSMAGeoCoordinate`
-

**Comment by Durborough** [comment]
**In GeoServices ist folgendes komisch:**

- [x] `reverse:withZoom` ist zu lang. Wir haben keine Einkürzungsmethoden gefunden, da sonst die Funktionalität wegfallen würde, an Ort und Stelle den Pin anzuzeigen, wo man hingeklickt hat, selbst wenn der Ort der gefunden wurde etwas daneben liegt. Zudem wäre das Error Handling nur outsourcebar, wenn man sehr viele Sachen übergibt, was die Methode nicht kürzer machen würde
- [x] `getCenterGeoCoordinates` kann man evtl einkürzen mit zugriff auf das Center der Bounding Box der Route. Das hat aber beim ersten Versuch nicht funktioniert und war leicht off... :/
- [x] `getRouteDistanceFrom: Json`, `getRouteDurationFrom: Json`, `getWaypointsFrom: Json` verletzen Law of Demeter. Lösung ist Aufspaltung, wodurch aber das Hantieren mit inneren Attributen im Json nicht besser wird, sondern das ganze nur unverständlicher auf mehr Methoden aufgeteilt wird.
- [x] Defines = but not hash Kategorie in possible bugs. Wir wissen nicht wie relevant der possible bug ist, da alles ja funktioniert.
- [ ] `getDistanceAsString` und `getDurationAsString` haben nil checks drinne. Könnte man evtl. `distance` und `duration` von `SMARoute` auf `0` initialisieren? Dann würde dieser Check nicht benötigt werden. Was für Auswirkungen würde das haben?

**Comment by TimRiedel** [comment]
> * `reverse:withZoom` ist zu lang. Wir haben keine Einkürzungsmethoden gefunden, da sonst die Funktionalität wegfallen würde, an Ort und Stelle den Pin anzuzeigen, wo man hingeklickt hat, selbst wenn der Ort der gefunden wurde etwas daneben liegt. Zudem wäre das Error Handling nur outsourcebar, wenn man sehr viele Sachen übergibt, was die Methode nicht kürzer machen würde

Ich würds so lassen...ich find das jetzt nicht zu lang oder so, gerade wenn man durch das Einkürzen die Funktionalität verringern würde

> * getCenterGeoCoordinates kann man evtl einkürzen mit zugriff auf das Center der Bounding Box der Route. Das hat aber beim ersten Versuch nicht funktioniert und war leicht off... :/

Genauso hier...die Methode hat 7 Zeilen effektiven Code, der was macht...die Variablendeklarationen und den Kommentar ausgeschlossen. Also ich finde viel cleaner geht es eigentlich nicht.

**Comment by TimRiedel** [comment]
> * `getRouteDistanceFrom: Json`, `getRouteDurationFrom: Json`, `getWaypointsFrom: Json` verletzen Law of Demeter. Lösung ist Aufspaltung, wodurch aber das Hantieren mit inneren Attributen im Json nicht besser wird, sondern das ganze nur unverständlicher auf mehr Methoden aufgeteilt wird.

Ich würde das jetzt nicht als Law of Demeter Verletzung sehen, wenn man einfach auf ein Json Objekt zugreifen will und dafür halt alle geschachtelten Properties durchgehen muss. Genau deshalb haben wir damals den Code ja schon ausgelagert, und ich wüsste nicht, wie man das noch cleaner unterteilen will.
```smalltalk
getRouteDistanceFrom: aJson

	^ (((((aJson at: 'features') at: 1) at: 'properties') at: 'summary') at: 'distance') rounded
```

**Comment by TimRiedel** [comment]
> * `getDistanceAsString` und `getDurationAsString` haben nil checks drinne. Könnte man evtl. `distance` und `duration` von `SMARoute` auf `0` initialisieren? Dann würde dieser Check nicht benötigt werden. Was für Auswirkungen würde das haben?

Der Grund warum der Nil Check drin ist, ist dass das Window eine Route hat. Entweder man setzt die `route` im Window auf nil und muss dann dort checken, ob die Route nil ist oder man setzt sozusagen eine leere Route, die aber keine distance und duration hat. Würde man distance und duration auf 0 initialisieren, hätten wir dauerhaft im SMA Window die 0 für Distanz und Route im UI stehen.

**Comment by TimRiedel** [comment]
> * hints of meta Programming nochmal checken --> ist `perform:` genauso doof wie `sendTo:`?

Haben wir zumindest in SWA auch benutzt und es ist halt eine relativ cleane Möglichkeit auf dem MockObject Methoden auszuführen, ohne groß andere Dictionaries zu nutzen, die den Symbolen irgendwelche Methoden zuordnen. Man kommt da wahrscheinlich eh nicht drum rum, weil irgendwie muss man ja die exakte Methode ausführen, die einem das korrekte Json Objekt zurückgibt.

**Comment by TimRiedel** [comment]
> * inkonsequentes Naming pin oder marker z.B. in `selectedPin`, `buildPinSearchPanel`, etc.

Vielleicht um hier mal ein bisschen mit den Namenskonventionen aufzuräumen. Im `GeoService` Package reden wir meist von Locations, die speichern einfach nur alle zu einer Location gehörigen Daten. Im `Core -> Window` reden wir über Pins, weil Richards Idee ursprünglich war, um die Location noch ein Wrapper Objekt zu bauen, sodass dort dann relevante Daten für das UI usw. gespeichert werden können. Diese sollten dann `Pins` heißen und suggerieren, dass sie noch mehr Daten beinhalten, bspw. in welcher Pin Liste der Pin liegt (bspw. man hätte eine Favoriten Liste). `Pins` sind aber momentan auch nur Locations. Auf dem `TiledMapMorph` reden wir über Marker, weil die dort gewählten Daten in einem TiledMapMorph spezifischen Format gespeichert werden.

Mir ist jetzt keine Methode im Core Window aufgefallen, wo noch Marker drin steht, hast du dafür ein konkretes Beispiel?

**Comment by TimRiedel** [comment]
> * `searchDirections` und `searchLocation` haben leichte Code Dopplung und sind sehr lang besonders `searchDirections`

Hab mal `searchDirections` etwas verkürzt. Wäre aber jetzt fine mit den Methodenlängen...insbesondere `searchLocation` find ich voll in Ordnung. `searchDirection` ist immer noch lang, aber das entsteht halt durch das ganze Error Handling und ich weiß nicht, wie wir das noch ordentlich auslagern könnten, ohne das Window komplett zu zucluttern.

**Comment by TimRiedel** [comment]
> * `classVariableNames: 'SavedPins'` --> Groß oder klein schreiben, wenn wir die `apiKey:` Funktionen der APIs klein schreiben vorne?

Ich hatte eigentlich in Erinnerung, dass Klassenvariablen vorne groß geschrieben werden...so steht es auch im Styleguide. Da wir aber konsistent die Klassenseitigen Accessors klein schreiben (auch bei den APIs), aber die tatsächlichen Variablen in den Accessorn groß, könnte man es auch so belassen.

**Comment by TimRiedel** [comment]
> * Defines = but not hash Kategorie in possible bugs. Wir wissen nicht wie relevant der possible bug ist, da alles ja funktioniert.

Hab ich gefixt, indem ich einfach das Hashing vom Punkt übernommen habe.

**Comment by Durborough** [comment]
- [ ] `drawMarker: on:` und `drawRouteLine: on:` sind auf dem `SMATiledMapsMorph`. man könnte das wissen wie die sich malen auf die Marker und die route line selbst verlegen? Zudem sind `color` Attribute von beiden auf den Objekten selbst gespeichert, aber die Labelfarbe dann nicht, genauso wie bei der `SMARouteLine` die Breite der Linie nicht auf dem Objekt sondern in der draw Funktion liegt, die woanders gespeichert wird...
- [ ] `ExpiringValue` `value` (müsste in evaluating) und `SMATiledMapMorph`  `center` sowie `center:` (müssten in geometry) und  `drawOn:` (müsste in drawing) sind inkonsistent klassifiziert, ist aber historisch gewachsen und keine Ahnung, ob die da besser aufgehoben wären? Wenn die `drawOn:` Moethode umziehen sollte müssten auch die anderen drawing Methoden umziehen.
- [x] Occurences of Global State on the Class site ist jeweils für SMAMapTileLoader und APIs vorhanden
- [x] Instance var access ist richtig viel vorhanden in altem code... Wie gehen wir damit um? Manche Sachen sind einfach zu ändern. Bei anderen würden wir uns nil checks einhandeln. Beim `initialize` des `SMATiledMapMorph` gibt esdie Problematik, dass nur direkt auf `zoom` und `center` zugegriffen werden kann, weil sonst `layoutChanged` aufgerufen wird, wenn man über die accessor geht, da diese Methode immer als Nebeneffekt aufgerufen wird.... Da aber `layoutChanged` bestimmte Werte braucht, wie die `tileSource,` die noch nicht initialisiert sind zu diesem Zeitpunkt, stürzt das Programm ab... Wenn man nun aber die `tileSource` zuerst initialisiert über die Accessor Methoden, dann benötigt dies wiederum `zoom`, da auch hier Layout changed aufgerufen wird... Wie soll man diese Zirkelbeziehung auflösen ohne super viele Methoden anzufassen, die wir davor nicht angefasst haben???
- [x] methods without senders gibt es viele. Wir sind uns unklar welche davon gelöscht werden können, da manche Accessors sind für Instanzvariabeln auf die sonst direkt zugegriffen wird und sonst Code der Legacy Code ist.

**Comment by TimRiedel** [comment]
> - [ ] `drawMarker: on:` und `drawRouteLine: on:` sind auf dem `SMATiledMapsMorph`. man könnte das wissen wie die sich malen auf die Marker und die route line selbst verlegen? Zudem sind `color` Attribute von beiden auf den Objekten selbst gespeichert, aber die Labelfarbe dann nicht, genauso wie bei der `SMARouteLine` die Breite der Linie nicht auf dem Objekt sondern in der draw Funktion liegt, die woanders gespeichert wird...
> 

Ich glaub das auslagern der Methoden wird schwierig, weil die brauchen doch ein Canvas, was von der World kommt und in 'World doOneCycle' oder so ähnlich aufgerufen wird.

**Comment by Durborough** [comment]
> > * [ ]  `drawMarker: on:` und `drawRouteLine: on:` sind auf dem `SMATiledMapsMorph`. man könnte das wissen wie die sich malen auf die Marker und die route line selbst verlegen? Zudem sind `color` Attribute von beiden auf den Objekten selbst gespeichert, aber die Labelfarbe dann nicht, genauso wie bei der `SMARouteLine` die Breite der Linie nicht auf dem Objekt sondern in der draw Funktion liegt, die woanders gespeichert wird...
> 
> Ich glaub das auslagern der Methoden wird schwierig, weil die brauchen doch ein Canvas, was von der World kommt und in 'World doOneCycle' oder so ähnlich aufgerufen wird.

Man könnte halt sagen, dass die `SMAMarker` und `SMARouteLine` eine `drawOn: aCanvas` Methode bekommen. Diese kann dann statt `drawMarker: aMarker on: aCanvas` aufgerufen werden, indem man `aMarker drawOn: aCanvas` aufruft. Dadurch würden sich die Marker selbst zeichnen. Das würde für höhere Coherence sorgen und weniger Coupling. Zudem würden Funktionalitäten vom `TiledMapMorph` runterwandern, die ihm eigentlich nicht gehören. Und die `Marker` und `RouteLine` wären keine Klassen mehr, die einfach nur Wissen wrappen, sondern die echte Aufgaben haben. Aber dann müssten sich halt auch alle anderen Sachen eigentlich selbst zeichnen, was nochmal ein größerer Refactor ist (?), weil auch die `Tiles` sich dann selber zeichnen sollten.

**Comment by richartkeil** [comment]
> > > * [ ]  `drawMarker: on:` und `drawRouteLine: on:` sind auf dem `SMATiledMapsMorph`. man könnte das wissen wie die sich malen auf die Marker und die route line selbst verlegen? Zudem sind `color` Attribute von beiden auf den Objekten selbst gespeichert, aber die Labelfarbe dann nicht, genauso wie bei der `SMARouteLine` die Breite der Linie nicht auf dem Objekt sondern in der draw Funktion liegt, die woanders gespeichert wird...
> > 
> > Ich glaub das auslagern der Methoden wird schwierig, weil die brauchen doch ein Canvas, was von der World kommt und in 'World doOneCycle' oder so ähnlich aufgerufen wird.
>
> Man könnte halt sagen, dass die `SMAMarker` und `SMARouteLine` eine `drawOn: aCanvas` Methode bekommen. Diese kann dann statt `drawMarker: aMarker on: aCanvas` aufgerufen werden, indem man `aMarker drawOn: aCanvas` aufruft. Dadurch würden sich die Marker selbst zeichnen. Das würde für höhere Coherence sorgen und weniger Coupling. Zudem würden Funktionalitäten vom `TiledMapMorph` runterwandern, die ihm eigentlich nicht gehören. Und die `Marker` und `RouteLine` wären keine Klassen mehr, die einfach nur Wissen wrappen, sondern die echte Aufgaben haben. Aber dann müssten sich halt auch alle anderen Sachen eigentlich selbst zeichnen, was nochmal ein größerer Refactor ist (?), weil auch die `Tiles` sich dann selber zeichnen sollten.

Würde sagen dass das aufgrund der Zeit jetzt nicht mehr umsetzbar ist, auch wenn es eigentlich sinnig wäre.

> - [x] methods without senders gibt es viele. Wir sind uns unklar welche davon gelöscht werden können, da manche Accessors sind für Instanzvariabeln auf die sonst direkt zugegriffen wird und sonst Code der Legacy Code ist.

Was meinst Du denn damit genau? Man könnte doch zumindest die Nicht-Accessor Methods direkt löschen, oder?

> - [x] Instance var access ist richtig viel vorhanden in altem code... Wie gehen wir damit um? Manche Sachen sind einfach zu ändern. Bei anderen würden wir uns nil checks einhandeln. Beim initialize des SMATiledMapMorph gibt esdie Problematik, dass nur direkt auf zoom und center zugegriffen werden kann, weil sonst layoutChanged aufgerufen wird, wenn man über die accessor geht, da diese Methode immer als Nebeneffekt aufgerufen wird.... Da aber layoutChanged bestimmte Werte braucht, wie die tileSource, die noch nicht initialisiert sind zu diesem Zeitpunkt, stürzt das Programm ab... Wenn man nun aber die tileSource zuerst initialisiert über die Accessor Methoden, dann benötigt dies wiederum zoom, da auch hier Layout changed aufgerufen wird... Wie soll man diese Zirkelbeziehung auflösen ohne super viele Methoden anzufassen, die wir davor nicht angefasst haben???

Könnte man nicht einen `zoomWithoutChange:` und `centerWithoutChange:` Accessor einführen? Dann sollte zumindest klar sein, dass die keine Layout Side Effects haben und man verhindert den Zugriff auf rohe Vars.

Bei den restlichen Punkten der Liste würde ich sagen, dass die so große Auswirkungen haben, dass wir das in der Zeit jetzt nicht mehr angehen sollten.

**Comment by LeoKohlenberg** [comment]
> > > > * [ ]   `drawMarker: on:` und `drawRouteLine: on:` sind auf dem `SMATiledMapsMorph`. man könnte das wissen wie die sich malen auf die Marker und die route line selbst verlegen? Zudem sind `color` Attribute von beiden auf den Objekten selbst gespeichert, aber die Labelfarbe dann nicht, genauso wie bei der `SMARouteLine` die Breite der Linie nicht auf dem Objekt sondern in der draw Funktion liegt, die woanders gespeichert wird...
> > > 
> > > 
> > > Ich glaub das auslagern der Methoden wird schwierig, weil die brauchen doch ein Canvas, was von der World kommt und in 'World doOneCycle' oder so ähnlich aufgerufen wird.
> > 
> > 
> > Man könnte halt sagen, dass die `SMAMarker` und `SMARouteLine` eine `drawOn: aCanvas` Methode bekommen. Diese kann dann statt `drawMarker: aMarker on: aCanvas` aufgerufen werden, indem man `aMarker drawOn: aCanvas` aufruft. Dadurch würden sich die Marker selbst zeichnen. Das würde für höhere Coherence sorgen und weniger Coupling. Zudem würden Funktionalitäten vom `TiledMapMorph` runterwandern, die ihm eigentlich nicht gehören. Und die `Marker` und `RouteLine` wären keine Klassen mehr, die einfach nur Wissen wrappen, sondern die echte Aufgaben haben. Aber dann müssten sich halt auch alle anderen Sachen eigentlich selbst zeichnen, was nochmal ein größerer Refactor ist (?), weil auch die `Tiles` sich dann selber zeichnen sollten.
> 
> Würde sagen dass das aufgrund der Zeit jetzt nicht mehr umsetzbar ist, auch wenn es eigentlich sinnig wäre.

+1

> 
> > * [x]  methods without senders gibt es viele. Wir sind uns unklar welche davon gelöscht werden können, da manche Accessors sind für Instanzvariabeln auf die sonst direkt zugegriffen wird und sonst Code der Legacy Code ist.
> 
> Was meinst Du denn damit genau? Man könnte doch zumindest die Nicht-Accessor Methods direkt löschen, oder?

+1, Nicht-Accessor Methods ohne Senders würde ich löschen und Accessors ohne Senders würde ich der Vollständigkeit halber drin lassen. In unseren Methoden sollten wir natürlich Accessors verwenden, in Methoden, die wir nicht angefasst haben, würde ich direkten Zugriffe lassen

> 
> > * [x]  Instance var access ist richtig viel vorhanden in altem code... Wie gehen wir damit um? Manche Sachen sind einfach zu ändern. Bei anderen würden wir uns nil checks einhandeln. Beim initialize des SMATiledMapMorph gibt esdie Problematik, dass nur direkt auf zoom und center zugegriffen werden kann, weil sonst layoutChanged aufgerufen wird, wenn man über die accessor geht, da diese Methode immer als Nebeneffekt aufgerufen wird.... Da aber layoutChanged bestimmte Werte braucht, wie die tileSource, die noch nicht initialisiert sind zu diesem Zeitpunkt, stürzt das Programm ab... Wenn man nun aber die tileSource zuerst initialisiert über die Accessor Methoden, dann benötigt dies wiederum zoom, da auch hier Layout changed aufgerufen wird... Wie soll man diese Zirkelbeziehung auflösen ohne super viele Methoden anzufassen, die wir davor nicht angefasst haben???
> 
> Könnte man nicht einen `zoomWithoutChange:` und `centerWithoutChange:` Accessor einführen? Dann sollte zumindest klar sein, dass die keine Layout Side Effects haben und man verhindert den Zugriff auf rohe Vars.

Gute Idee eigentlich, wäre die Frage, ob man nicht die normalen Accessors einfach ohne Seiteneffekte baut und extra Accessors einführt, welche die Seiteneffekte berücksichtigen, damit die normalen Accessors das tun, was man erwarten würde.

> 
> Bei den restlichen Punkten der Liste würde ich sagen, dass die so große Auswirkungen haben, dass wir das in der Zeit jetzt nicht mehr angehen sollten.

+1
